"""empty message

Revision ID: 7a9d92b50ec5
Revises: 0d155a00bc66
Create Date: 2023-06-14 10:36:22.243205

"""
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy import func
from sqlalchemy import text
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7a9d92b50ec5'
down_revision = '0d155a00bc66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_token',
                                     postgresql.UUID(as_uuid=True),
                                     nullable=False,
                                     server_default=text("uuid_generate_v4()"),))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_token')
    # ### end Alembic commands ###
